no-pidfile yes
no-daemon yes
log-level warn
log-syslog yes

cache-persist yes
cache-file /var/cache/smartdns/smartdns.cache
cache-size 15000
dualstack-ip-selection yes
dualstack-ip-selection-threshold 500
prefetch-domain yes
rr-ttl-min 10

server 119.29.29.29 -bootstrap-dns
server 119.28.28.28 -bootstrap-dns
server 233.6.6.6 -bootstrap-dns
server 233.5.5.5 -bootstrap-dns
server 119.29.29.29 -fallback
server 119.28.28.28 -fallback
server 233.6.6.6 -fallback
server 233.5.5.5 -fallback

group-begin common
bind [::1]:5365
bind-tcp [::1]:5365
bind 127.0.0.1:5365
bind-tcp 127.0.0.1:5365

server-https https://doh.pub/dns-query
server-https https://dns.alidns.com/dns-query
server-https https://doh.360.cn
group-end

group-begin public
bind [::1]:5370
bind-tcp [::1]:5370
bind 127.0.0.1:5370
bind-tcp 127.0.0.1:5370

server-https https://dns.google/dns-query
server-https https://dns.cloudflare.com/dns-query
group-end

group-begin main
bind [::1]:53
bind-tcp [::1]:53
bind 127.0.0.1:53
bind-tcp 127.0.0.1:53

server-https https://doh.pub/dns-query
server-https https://dns.alidns.com/dns-query
server-https https://doh.360.cn

address /github.com/127.0.0.1
address /githubusercontent.com/127.0.0.1
address /githubassets.com/127.0.0.1
address /github.io/127.0.0.1
address /steamcommunity.com/127.0.0.1
address /pixiv.net/127.0.0.1
address /pixivsketch.net/127.0.0.1
address /pximg.net/127.0.0.1
group-end
