upstream pixiv_net {
    zone pixiv_net 64k;
    server 210.140.139.151:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.152:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.153:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.154:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.155:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.156:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.157:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.158:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.159:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.160:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.161:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.162:443 max_fails=2 fail_timeout=30s;
    server pixiv.net:443 resolve max_fails=2 fail_timeout=30s;
    server pixiv.org:443 resolve max_fails=2 fail_timeout=30s;
    hash $connection consistent;
    keepalive 16;
}

upstream pximg_net {
    zone pximg_net 64k;
    server 210.140.139.131:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.132:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.133:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.134:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.135:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.136:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.137:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.138:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.149:443 max_fails=2 fail_timeout=30s;
    server 210.140.139.150:443 max_fails=2 fail_timeout=30s;
    server pximg.net:443 resolve max_fails=2 fail_timeout=30s;
    keepalive 16;
    least_conn;
}

upstream fanbox_cc {
    zone fanbox_cc 64k;
    server 172.64.146.116:443 max_fails=2 fail_timeout=30s;
    server 172.64.146.247:443 max_fails=2 fail_timeout=30s;
    server fanbox.cc:443 resolve max_fails=2 fail_timeout=30s;
    keepalive 16;
}

server {
    http2 on;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.pixiv.net pixiv.net pixiv.org;
    server_name *.pixiv.net *.pixiv.org;

    location / {
        proxy_pass https://pixiv_net;
        include share_proxy_buffer.conf;
    }
}

server {
    http2 on;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name pximg.net;
    server_name *.pximg.net;

    location / {
        proxy_pass https://pximg_net;
        include share_proxy_buffer.conf;
    }
}

server {
    http2 on;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name fanbox.cc;
    server_name *.fanbox.cc;

    location / {
        proxy_pass https://fanbox_cc;
        include share_proxy_buffer.conf;
    }
}
